mail:
  smtp: mail.tf2mv.com
  from: no-reply@tf2mv.com
  errors: errors@tf2mv.com
  errorsubject: tf2mv Error Logged

database:
  users:
    tf2mv: &tf2mv
      username: tf2mv
      password:
    item_found: &itemfound
      username: item_found
      password:
  instances:
    production: &production
      hostname: mysql.tf2mv.com
      database: tf2mv
      users:
        writeonly: *itemfound
        primary: *tf2mv
    test: &test
      hostname: mysql.connett.net
      database: test_tf2mv
      users:
        writeonly: *itemfound
        primary: *tf2mv

application:
  interpreter: /usr/bin/python
  url: http://localhost
  port: 5000
  database:
    instance: *test
    poolsize: 1
